dismiss:
  description: Dismiss a html5 notification.
  fields:
    target:
      description: An array of targets. Optional.
      example: ["my_phone", "my_tablet"]
    data:
      description: Extended information of notification. Supports tag. Optional.
      example: '{ "tag": "tagname" }'
