# Describes the format for available Netatmo services
set_camera_light:
  description: Set the camera light mode
  target:
    entity:
      integration: netatmo
      domain: light
  fields:
    camera_light_mode:
      name: Camera light mode
      description: Outdoor camera light mode (on/off/auto)
      example: auto
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
            - "auto"

set_schedule:
  description: Set the heating schedule
  target:
    entity:
      integration: netatmo
      domain: climate
  fields:
    schedule_name:
      description: Schedule name
      example: Standard
      required: true
      selector:
        text:

set_persons_home:
  description: Set a list of persons as at home. Person's name must match a name known by the Welcome Camera
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    persons:
      description: List of names
      example: Bob
      required: true
      selector:
        text:

set_person_away:
  description: Set a person away. If no person is set the home will be marked as empty. Person's name must match a name known by the Welcome Camera
  target:
    entity:
      integration: netatmo
      domain: camera
  fields:
    person:
      description: Person's name (optional)
      example: Bob
      selector:
        text:

register_webhook:
  description: Register webhook

unregister_webhook:
  description: Unregister webhook
