FROM mcr.microsoft.com/vscode/devcontainers/python:0-3.9

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        libudev-dev \
        libavformat-dev \
        libavcodec-dev \
        libavdevice-dev \
        libavutil-dev \
        libswscale-dev \
        libswresample-dev \
        libavfilter-dev \
        libpcap-dev \
        git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src

# Setup opp-release
RUN git clone --depth 1 https://github.com/openpeerpower/opp-release \
    && pip3 install -e opp-release/

WORKDIR /workspaces

# Install Python dependencies from requirements
COPY requirements.txt requirements_test.txt requirements_test_pre_commit.txt ./
COPY openpeerpower/package_constraints.txt openpeerpower/package_constraints.txt
RUN pip3 install -r requirements.txt \
   && pip3 install -r requirements_test.txt \
   && rm -rf requirements.txt requirements_test.txt requirements_test_pre_commit.txt openpeerpower/

# Set the default shell to bash instead of sh
ENV SHELL /bin/bash
