sync:
  description: Syncs the remote's configuration.
  fields:
    entity_id:
      description: Name(s) of entities to sync.
      example: "remote.family_room"

change_channel:
  description: Sends change channel command to the Harmony HUB
  fields:
    entity_id:
      description: Name(s) of Harmony remote entities to send change channel command to
      example: "remote.family_room"
    channel:
      description: Channel number to change to
      example: "200"
