set_vane_horizontal:
  description: Sets horizontal vane position.
  fields:
    entity_id:
      description: Name of the target entity
      example: "climate.ac_1"
    position:
      description: >
        Horizontal vane position. Possible options can be found in the
        vane_horizontal_positions state attribute.
      example: "auto"

set_vane_vertical:
  description: Sets vertical vane position.
  fields:
    entity_id:
      description: Name of the target entity
      example: "climate.ac_1"
    position:
      description: >
        Vertical vane position. Possible options can be found in the
        vane_vertical_positions state attribute.
      example: "auto"
