capture_image:
  description: Request a new image capture from a camera device.
  fields:
    entity_id:
      description: Entity id of the camera to request an image.
      example: camera.downstairs_motion_camera
change_setting:
  description: Change an Abode system setting.
  fields:
    setting:
      description: Setting to change.
      example: beeper_mute
    value:
      description: Value of the setting.
      example: "1"
trigger_automation:
  description: Trigger an Abode automation.
  fields:
    entity_id:
      description: Entity id of the automation to trigger.
      example: switch.my_automation
