# Describes the format for available fan services
set_speed:
  description: Set fan speed
  target:
  fields:
    speed:
      name: Speed
      description: Speed setting.
      required: true
      example: "low"
      selector:
        text:

set_preset_mode:
  description: Set preset mode for a fan device
  target:
  fields:
    preset_mode:
      name: Preset mode
      description: New value of preset mode.
      required: true
      example: "auto"
      selector:
        text:

set_percentage:
  description: Set fan speed percentage
  target:
  fields:
    percentage:
      name: Percentage
      description: Percentage speed setting.
      required: true
      example: 25
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

turn_on:
  description: Turn fan on
  target:
  fields:
    speed:
      name: Speed
      description: Speed setting.
      example: "high"
    percentage:
      name: Percentage
      description: Percentage speed setting.
      example: 75
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
    preset_mode:
      name: Preset mode
      description: Preset mode setting.
      example: "auto"
      selector:
        text:

turn_off:
  description: Turn fan off
  target:

oscillate:
  description: Oscillate the fan
  target:
  fields:
    oscillating:
      name: Oscillating
      description: Flag to turn on/off oscillation.
      required: true
      example: true
      selector:
        boolean:

toggle:
  description: Toggle the fan on/off
  target:

set_direction:
  description: Set the fan rotation
  target:
  fields:
    direction:
      name: Direction
      description: The direction to rotate.
      required: true
      example: "forward"
      selector:
        select:
          options:
            - "forward"
            - "reverse"

increase_speed:
  description: Increase the speed of the fan by one speed or a percentage_step.
  fields:
    entity_id:
      description: Name(s) of the entities to increase speed
      example: "fan.living_room"
    percentage_step:
      advanced: true
      required: false
      description: Increase speed by a percentage. Should be between 0..100. [optional]
      example: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

decrease_speed:
  description: Decrease the speed of the fan by one speed or a percentage_step.
  fields:
    entity_id:
      description: Name(s) of the entities to decrease speed
      example: "fan.living_room"
    percentage_step:
      advanced: true
      required: false
      description: Decrease speed by a percentage. Should be between 0..100. [optional]
      example: 50
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider
