speedtest:
  description: Immediately execute a speed test with iperf3
  fields:
    host:
      description: The host name of the iperf3 server (already configured) to run a test with.
      example: "iperf.he.net"
