# Describes the format for available recorder services

purge:
  description: Start purge task - to clean up old data from your database
  fields:
    keep_days:
      name: Days to keep
      description: Number of history days to keep in database after purge.
      example: 2
      selector:
        number:
          min: 0
          max: 365
          step: 1
          unit_of_measurement: days
          mode: slider

    repack:
      name: Repack
      description:
        Attempt to save disk space by rewriting the entire database file.
      example: true
      default: false
      selector:
        boolean:
