join:
  description: Group players together.
  fields:
    entity_id:
      description: id of the player that will be the master of the group.
      example: "media_player.study"
    join_ids:
      description: id(s) of the players that will join the master.
      example: "['media_player.bedroom', 'media_player.kitchen']"

unjoin:
  description: Remove players from a group.
  fields:
    entity_id:
      description: id of the player that is the master of the group..
      example: "media_player.study"
    unjoin_ids:
      description: Optional id(s) of the players that will be unjoined from the group. If not specified, all players will be unjoined from the master.
      example: "['media_player.bedroom', 'media_player.kitchen']"

transfer:
  description: Transfer playback from one player to another.
  fields:
    entity_id:
      description: id of the source player.
      example: "media_player.bedroom"
    transfer_id:
      description: id of the destination player.
      example: "media_player.study"
