select_cmode:
  description: Select Color mode of Epson projector
  fields:
    entity_id:
      description: Name of projector
      example: "media_player.epson_projector"
    cmode:
      description: Name of Cmode
      example: "cinema"
