# Support for (EMEA/EU-based) Honeywell TCC climate systems.
# Describes the format for available services

set_system_mode:
  description: >-
    Set the system mode, either indefinitely, or for a specified period of time, after
    which it will revert to Auto. Not all systems support all modes.
  fields:
    mode:
      description: "One of: Auto, AutoWithEco, Away, DayOff, HeatingOff, or Custom."
      example: Away
    period:
      description: >-
        A period of time in days; used only with Away, DayOff, or Custom. The system
        will revert to Auto at midnight (up to 99 days, today is day 1).
      example: '{"days": 28}'
    duration:
      description: The duration in hours; used only with AutoWithEco (up to 24 hours).
      example: '{"hours": 18}'

reset_system:
  description: >-
    Set the system to Auto mode and reset all the zones to follow their schedules.
    Not all Evohome systems support this feature (i.e. AutoWithReset mode).

refresh_system:
  description: >-
    Pull the latest data from the vendor's servers now, rather than waiting for the
    next scheduled update.

set_zone_override:
  description: >-
    Override a zone's setpoint, either indefinitely, or for a specified period of
    time, after which it will revert to following its schedule.
  fields:
    entity_id:
      description: The entity_id of the Evohome zone.
      example: climate.bathroom
    setpoint:
      description: The temperature to be used instead of the scheduled setpoint.
      example: 5.0
    duration:
      description: >-
        The zone will revert to its schedule after this time. If 0 the change is until
        the next scheduled setpoint.
      example: '{"minutes": 135}'

clear_zone_override:
  description: Set a zone to follow its schedule.
  fields:
    entity_id:
      description: The entity_id of the zone.
      example: climate.bathroom
