toggle:
  name: Toggle
  description: Toggle alert's notifications.
  target:

turn_off:
  name: Turn off
  description: Silence alert's notifications.
  target:

turn_on:
  name: Turn on
  description: Reset alert's notifications.
  target:
