# Describes the format for available component services
process:
  description: Launch a conversation from a transcribed text
  fields:
    text:
      name: Text
      description: Transcribed text
      example: Turn all lights on
      selector:
        text:
