disable:
  description: Disable configured Pi-hole(s) for an amount of time
  fields:
    entity_id:
      description: Target switch entity
      example: switch.pi_hole
    duration:
      description: Time that the Pi-hole should be disabled for
      example: "00:00:15"
