# Describes the format for available webostv services

button:
  description: "Send a button press command."
  fields:
    entity_id:
      description: Name(s) of the webostv entities where to run the API method.
      example: "media_player.living_room_tv"
    button:
      description: >-
        Name of the button to press.  Known possible values are
        LEFT, RIGHT, DOWN, UP, HOME, MENU, BACK, ENTER, DASH, INFO, ASTERISK, CC, EXIT,
        MUTE, RED, GREEN, BLUE, VOLUMEUP, VOLUMEDOWN, CHANNELUP, CHANNELDOWN,
        PLAY, PAUSE, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9
      example: "LEFT"

command:
  description: "Send a command."
  fields:
    entity_id:
      description: Name(s) of the webostv entities where to run the API method.
      example: "media_player.living_room_tv"
    command:
      description: >-
        Endpoint of the command. Known valid endpoints are listed in
        https://github.com/TheRealLink/pylgtv/blob/master/pylgtv/endpoints.py
      example: "system.launcher/open"
    payload:
      description: >-
        An optional payload to provide to the endpoint in the format of key value pair(s).
      example: >-
        target: https://www.google.com

select_sound_output:
  description: "Send the TV the command to change sound output."
  fields:
    entity_id:
      description: Name(s) of the webostv entities to change sound output on.
      example: "media_player.living_room_tv"
    sound_output:
      description: Name of the sound output to switch to.
      example: "external_speaker"
