# Describes the format for available lock services

clear_usercode:
  description: Clear a usercode from lock.
  fields:
    node_id:
      description: Node id of the lock.
      example: 18
    code_slot:
      description: Code slot to clear code from.
      example: 1

get_usercode:
  description: Retrieve a usercode from lock.
  fields:
    node_id:
      description: Node id of the lock.
      example: 18
    code_slot:
      description: Code slot to retrieve a code from.
      example: 1

lock:
  name: Lock
  description: Lock all or specified locks.
  target:
  fields:
    code:
      name: Code
      description: An optional code to lock the lock with.
      example: 1234
      selector:
        text:

open:
  name: Open
  description: Open all or specified locks.
  target:
  fields:
    code:
      name: Code
      description: An optional code to open the lock with.
      example: 1234
      selector:
        text:

set_usercode:
  name: Set usercode
  description: Set a usercode to lock.
  fields:
    node_id:
      description: Node id of the lock.
      example: 18
    code_slot:
      description: Code slot to set the code.
      example: 1
    usercode:
      description: Code to set.
      example: 1234

unlock:
  name: Unlock
  description: Unlock all or specified locks.
  target:
  fields:
    code:
      name: Code
      description: An optional code to unlock the lock with.
      example: 1234
      selector:
        text:
