name: Build images

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  release:
    types: ["published"]
  schedule:
    - cron: "0 0 1 * *"

env:
  BUILD_TYPE: core
  DEFAULT_PYTHON: 3.8

jobs:
  init:
    name: Initialize build
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.info.outputs.architectures }}
      version: ${{ steps.version.outputs.version }}
      channel: ${{ steps.version.outputs.channel }}
      publish: ${{ steps.version.outputs.publish }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4.4.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Get information
        id: info
        uses: openpeerpower/actions/helpers/info@main

      - name: Get version
        id: version
        uses: openpeerpower/actions/helpers/version@main
        with:
          type: ${{ env.BUILD_TYPE }}

      - name: Verify version
        uses: openpeerpower/actions/helpers/verify-version@main
        with:
          ignore-dev: true

  build_python:
    name: Build PyPi package
    needs: init
    runs-on: ubuntu-latest
    if: needs.init.outputs.publish == 'true'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4.4.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Build package
        shell: bash
        run: |
          pip install twine wheel
          python setup.py sdist bdist_wheel

      - name: Upload package
        shell: bash
        run: |
          export TWINE_USERNAME="__token__"
          export TWINE_PASSWORD="${{ secrets.TWINE_TOKEN }}"

          twine upload dist/* --skip-existing

  build_base:
    name: Build ${{ matrix.arch }} base core image
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ${{ fromJson(needs.init.outputs.architectures) }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        if: needs.init.outputs.channel == 'dev'
        uses: actions/setup-python@v4.4.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Adjust nightly version
        if: needs.init.outputs.channel == 'dev'
        shell: bash
        run: |
          python3 -m pip install packaging
          python3 -m pip install .
          python3 script/version_bump.py nightly
          version="$(python setup.py -V)"

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build base image
        uses: openpeerpower/builder@2021.7.3
        with:
          args: |
            $BUILD_ARGS \
            --${{ matrix.arch }} \
            --target /data \
            --generic ${{ needs.init.outputs.version }}

  build_machine:
    name: Build ${{ matrix.machine }} machine core image
    needs: ["init", "build_base"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        machine:
          - generic-x86-64
          - qemuarm
          - qemuarm-64
          - qemux86
          - qemux86-64
          - raspberrypi
          - raspberrypi2
          - raspberrypi3
          - raspberrypi3-64
          - raspberrypi4
          - raspberrypi4-64
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build base image
        uses: openpeerpower/builder@2021.7.3
        with:
          args: |
            $BUILD_ARGS \
            --target /data/machine \
            --machine "${{ needs.init.outputs.version }}=${{ matrix.machine }}"

  publish_ha:
    name: Publish version files
    needs: ["init", "build_machine"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Initialize git
        uses: openpeerpower/actions/helpers/git-init@main
        with:
          name: ${{ secrets.GIT_NAME }}
          email: ${{ secrets.GIT_EMAIL }}
          token: ${{ secrets.GIT_TOKEN }}

      - name: Update version file
        uses: openpeerpower/actions/helpers/version-push@main
        with:
          key: "openpeerpower[]"
          key-description: "Open Peer Power Core"
          version: ${{ needs.init.outputs.version }}
          channel: ${{ needs.init.outputs.channel }}

      - name: Update version file (stable -> beta)
        if: needs.init.outputs.channel == 'stable'
        uses: openpeerpower/actions/helpers/version-push@main
        with:
          key: "openpeerpower[]"
          key-description: "Open Peer Power Core"
          version: ${{ needs.init.outputs.version }}
          channel: beta

  publish_container:
    name: Publish meta container
    needs: ["init", "build_base"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4

      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ secrets.GIT_USER }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build Meta Image
        shell: bash
        run: |

          export DOCKER_CLI_EXPERIMENTAL=enabled

          function create_manifest() {
            local docker_reg=${1}
            local tag_l=${2}
            local tag_r=${3}

            docker manifest create "${docker_reg}/openpeerpower:${tag_l}" \
              "${docker_reg}/amd64-openpeerpower:${tag_r}" \
              "${docker_reg}/i386-openpeerpower:${tag_r}" \
              "${docker_reg}/armhf-openpeerpower:${tag_r}" \
              "${docker_reg}/armv7-openpeerpower:${tag_r}" \
              "${docker_reg}/aarch64-openpeerpower:${tag_r}"

            docker manifest annotate "${docker_reg}/openpeerpower:${tag_l}" \
              "${docker_reg}/amd64-openpeerpower:${tag_r}" \
              --os linux --arch amd64

            docker manifest annotate "${docker_reg}/openpeerpower:${tag_l}" \
              "${docker_reg}/i386-openpeerpower:${tag_r}" \
              --os linux --arch 386

            docker manifest annotate "${docker_reg}/openpeerpower:${tag_l}" \
              "${docker_reg}/armhf-openpeerpower:${tag_r}" \
              --os linux --arch arm --variant=v6

            docker manifest annotate "${docker_reg}/openpeerpower:${tag_l}" \
              "${docker_reg}/armv7-openpeerpower:${tag_r}" \
              --os linux --arch arm --variant=v7

            docker manifest annotate "${docker_reg}/openpeerpower:${tag_l}" \
              "${docker_reg}/aarch64-openpeerpower:${tag_r}" \
              --os linux --arch arm64 --variant=v8

            docker manifest push --purge "${docker_reg}/openpeerpower:${tag_l}"
          }

          function validate_image() {
            local image=${1}
            state="$(vcn authenticate --org openpeerpower.io --output json docker://${image} | jq '.verification.status // 2')"
            if [[ "${state}" != "0" ]]; then
              echo "Invalid signature!"
              exit 1
            fi
          }

          for docker_reg in "openpeerpower" "ghcr.io/openpeerpower"; do
            docker pull "${docker_reg}/amd64-openpeerpower:${{ needs.init.outputs.version }}"
            docker pull "${docker_reg}/i386-openpeerpower:${{ needs.init.outputs.version }}"
            docker pull "${docker_reg}/armhf-openpeerpower:${{ needs.init.outputs.version }}"
            docker pull "${docker_reg}/armv7-openpeerpower:${{ needs.init.outputs.version }}"
            docker pull "${docker_reg}/aarch64-openpeerpower:${{ needs.init.outputs.version }}"

            validate_image "${docker_reg}/amd64-openpeerpower:${{ needs.init.outputs.version }}"
            validate_image "${docker_reg}/i386-openpeerpower:${{ needs.init.outputs.version }}"
            validate_image "${docker_reg}/armhf-openpeerpower:${{ needs.init.outputs.version }}"
            validate_image "${docker_reg}/armv7-openpeerpower:${{ needs.init.outputs.version }}"
            validate_image "${docker_reg}/aarch64-openpeerpower:${{ needs.init.outputs.version }}"

            # Create version tag
            create_manifest "${docker_reg}" "${{ needs.init.outputs.version }}" "${{ needs.init.outputs.version }}"

            # Create general tags
            if [[ "${{ needs.init.outputs.version }}" =~ d ]]; then
              create_manifest "${docker_reg}" "dev" "${{ needs.init.outputs.version }}"
            elif [[ "${{ needs.init.outputs.version }}" =~ b ]]; then
              create_manifest "${docker_reg}" "beta" "${{ needs.init.outputs.version }}"
              create_manifest "${docker_reg}" "rc" "${{ needs.init.outputs.version }}"
            else
              create_manifest "${docker_reg}" "stable" "${{ needs.init.outputs.version }}"
              create_manifest "${docker_reg}" "latest" "${{ needs.init.outputs.version }}"
              create_manifest "${docker_reg}" "beta" "${{ needs.init.outputs.version }}"
              create_manifest "${docker_reg}" "rc" "${{ needs.init.outputs.version }}"
            fi
          done
