# Describes the format for available cover services

open_cover:
  name: Open
  description: Open all or specified cover.
  target:

close_cover:
  name: Close
  description: Close all or specified cover.
  target:

toggle:
  name: Toggle
  description: Toggle a cover open/closed.
  target:

set_cover_position:
  name: Set position
  description: Move to specific position all or specified cover.
  target:
  fields:
    position:
      name: Position
      description: Position of the cover
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

stop_cover:
  name: Stop
  description: Stop all or specified cover.
  target:

open_cover_tilt:
  name: Open tilt
  description: Open all or specified cover tilt.
  target:

close_cover_tilt:
  name: Close tilt
  description: Close all or specified cover tilt.
  target:

toggle_cover_tilt:
  name: Toggle tilt
  description: Toggle a cover tilt open/closed.
  target:

set_cover_tilt_position:
  name: Set tilt position
  description: Move to specific position all or specified cover tilt.
  target:
  fields:
    tilt_position:
      name: Tilt position
      description: Tilt position of the cover.
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

stop_cover_tilt:
  name: Stop tilt
  description: Stop all or specified cover.
  target:
