# Describes the format for available cover services

open_cover:
  description: Open all or specified cover
  target:

close_cover:
  description: Close all or specified cover
  target:

toggle:
  description: Toggles a cover open/closed
  target:

set_cover_position:
  description: Move to specific position all or specified cover
  target:
  fields:
    position:
      name: Position
      description: Position of the cover
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

stop_cover:
  description: Stop all or specified cover
  target:

open_cover_tilt:
  description: Open all or specified cover tilt
  target:

close_cover_tilt:
  description: Close all or specified cover tilt
  target:

toggle_cover_tilt:
  description: Toggle a cover tilt open/closed
  target:

set_cover_tilt_position:
  description: Move to specific position all or specified cover tilt
  target:
  fields:
    tilt_position:
      name: Tilt position
      description: Tilt position of the cover.
      required: true
      example: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"
          mode: slider

stop_cover_tilt:
  description: Stop all or specified cover
  target:
